name: Isoltec
favicon: null
layout_spectrum: 0.07042
typography_spectrum: 0.77845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#38cb00'
    - '#1c92d0'
    - '#000000'
    - '#0000ff'
    - '#0055aa'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
